### ISSUE TITLE
YAML updates

### ISSUE THREAD

**Issue by FedericoRondoni** [eurodatacube/eodash-catalog#105]
Hi @santilland and @lubojr
I'm opening this issue to keep track of the various things that are coming up while doing the yaml files sanitation. 

For the moment, I have two questions:

- In the C1, C2 and C3 yaml, there is this field that I don't think is shown in the dashboard.

> References:
>   - Name: AIS data
>     Url: https://www.imo.org/en/OurWork/Safety/Pages/AIS.aspx
>   - Name: TomTom data
>     Url: https://www.tomtom.com/products/traffic-and-travel-information/
>   - Name: Oxford University’s coronavirus government response tracker
>     Url: https://covidtracker.bsg.ox.ac.uk/

- I have to add a link for a notebook in a yaml file; which configuration option should I use?

**Comment by santilland** [comment]
Hello @FedericoRondoni we are not yet adding these references with the generator.
In principle generic "assets" should be fine to be described as that, i will look into adding this.
For a notebook link it depends if we intend for it to be executed on a processing service endpoint. If it is, we will need to make sure to implement a special service tag that allows execution of the notebook from within the client.

**Comment by FedericoRondoni** [comment]
Ok perfect, thanks!

Concerning the notebook, for instance, we should add this one https://eurodatacube.com/notebooks/contributions/Detect_Trucks_Sentinel2.ipynb to this part of the dashboard 
![image](https://github.com/eurodatacube/eodash-catalog/assets/72614374/e20e7939-3a2a-4e75-bc0b-f365e4aae0a5)

Do you think it is possible, and if yes, how?

**Comment by santilland** [comment]
@FedericoRondoni should the notebook be opened in a specific service? So, should clicking the button open the notebook on EDC? We could implement that.

**Comment by santilland** [comment]
Hello @FedericoRondoni i added now following configuration options:
https://github.com/eurodatacube/eodash-catalog/wiki/Reference
and 
https://github.com/eurodatacube/eodash-catalog/wiki/Service#eoxhub-notebook
i pulled in the updates also into this branch

**Comment by FedericoRondoni** [comment]
Hi @santilland the issue we encountered is with the indicator E13b. It seems that there are multiple E13b, and it is not clear which YAML file to use or which collection is the correct one. Can you please provide a mapping to the correct indicator?
Thanks!

**Comment by FedericoRondoni** [comment]
> Hello @FedericoRondoni i added now following configuration options: https://github.com/eurodatacube/eodash-catalog/wiki/Reference and https://github.com/eurodatacube/eodash-catalog/wiki/Service#eoxhub-notebook i pulled in the updates also into this branch

Also, did we merge this? Because I have an error with the pull request

**Comment by santilland** [comment]
Hello @FedericoRondoni as for the E13b we have following collections:
* https://github.com/eurodatacube/eodash-catalog/blob/main/collections/E13b_parked_planes.yaml
  - "main" E13b collection for the RACE instance
* https://github.com/eurodatacube/eodash-catalog/blob/main/collections/E13b_parked_airplanes.yaml
  - "main" E13b collection for the eodashboard (trilateral) instance
* https://github.com/eurodatacube/eodash-catalog/blob/main/collections/E13b_airport_throughput.yaml
  - additional collection of ICEYE data, that is similar to the one off images of ship detections for two locations in spain and germany (we gave this collection a new EodashIdentifier `E13b_airport_throughput` and i would propose to keep it as its own collection for now, as i could imagine on review we might want to remove it)

**Comment by santilland** [comment]
> Also, did we merge this? Because I have an error with the pull request

@FedericoRondoni i am not completely sure now from which branch the pull request started, would be great to merge the first pull request once we have the approval. 
In any case it seems the main issue here is that the Url parameter is expected to be written as `Url` and you have provided it as `URL`.

**Comment by FedericoRondoni** [comment]
> > Also, did we merge this? Because I have an error with the pull request
> 
> @FedericoRondoni i am not completely sure now from which branch the pull request started, would be great to merge the first pull request once we have the approval. In any case it seems the main issue here is that the Url parameter is expected to be written as `Url` and you have provided it as `URL`.

Ok clear, I will modify the Url. Thanks Daniel!

**Comment by FedericoRondoni** [comment]
Hi @santilland, I have a question related to the images inside the YAML files. 
Should we reference inside the YAML file all the images that we use in the descriptions or the field image in the YAML is for a specific use?

**Comment by lubojr** [comment]
@FedericoRondoni The `Image`: tag in the YAML will get displayed as the Thumbnail image for a collection in STAC Browser. https://radiantearth.github.io/stac-browser/#/external/eurodatacube.github.io/eodash-catalog/RACE/catalog.json We have mostly migrated the original race dashboard global indicators icons to change into these Thumbnails. I guess not all collection YAMLs need to have the Image tag though.
No need to link all images from the story here, as the purpose is different.

**Comment by FedericoRondoni** [comment]
> @FedericoRondoni The `Image`: tag in the YAML will get displayed as the Thumbnail image for a collection in STAC Browser. https://radiantearth.github.io/stac-browser/#/external/eurodatacube.github.io/eodash-catalog/RACE/catalog.json We have mostly migrated the original race dashboard global indicators icons to change into these Thumbnails. I guess not all collection YAMLs need to have the Image tag though. No need to link all images from the story here, as the purpose is different.

Thank @lubojr that's clear now!

**Comment by FedericoRondoni** [comment]
Hi @santilland one question:
How can I access the RACE dashboard where there are the various indicators that we have modified?

**Comment by lubojr** [comment]
You can see the latest state of the whole RACE dashboard on https://eodash-testing.eox.at/ui-panels-cat/
