### ISSUE TITLE
Water quality maps and sea surface temperature new AOI missing

### ISSUE THREAD

**Issue by AlessandroScremin** [eurodatacube/eodash-catalog#135]
@lubojr @santilland   CC: @dmoglioni 

I see htat the new AOIs (Portugal and Hamburg) for water quality maps from CNR are wrongly exposed both in eodashboard and Race

you see that filtering for Total suspended matter maps of ESA

There are only 4 AOI (out of 6)

![image](https://github.com/eurodatacube/eodash-catalog/assets/65602207/980d024d-fbc2-4e67-a500-0c9b18d7018b)

but when I zoom in I see the new aoi but not POI avaialbe

![image](https://github.com/eurodatacube/eodash-catalog/assets/65602207/5844a1ab-726a-43bb-84cd-44ec1a04a013)

What is needed to add the two new AOI as POI?

**Comment by lubojr** [comment]
@AlessandroScremin please update the configuration YAMLs with the new desired pois  in a new branch 

on these places
https://github.com/eurodatacube/eodash-catalog/blob/main/collections/N3a2_total_suspended_matter_tri_esa.yaml#L19
https://github.com/eurodatacube/eodash-catalog/blob/main/collections/N3a2_chl_concentration_tri_esa.yaml#L19

**Comment by lubojr** [comment]
@AlessandroScremin The build failed to run through https://github.com/eurodatacube/eodash-catalog/actions/runs/8967270206/job/24624466859 
the PR description collection names can not have the `.yaml` suffix and collections should be delimited by space ` `, not newline.
I have updated the PR description and rerun the pipeline now. On first glance it looks fine, so I will approve the PR and feel free to merge it whenever you want to. (I think you should have the permissions).

**Comment by lubojr** [comment]
Will get fixed when https://github.com/eurodatacube/eodash-catalog/pull/137 is merged. Closing the issue.
