### ISSUE TITLE
eodashboard Jaxa water quality maps last updates missing

### ISSUE THREAD

**Issue by AlessandroScremin** [eurodatacube/eodash-catalog#136]
@santilland @lubojr  cc: @dmoglioni @aapopescu 

Cioa Daniel and Lubo, two week ago I updated the maps from Jaxa water quality  till 24 February 2024, 00:00 but in the dashboards they are blocked till august 2023

Could you please check or tell me what to do to make the updates active?

this is the dashboard
![image](https://github.com/eurodatacube/eodash-catalog/assets/65602207/d8d11a87-e2b1-43e2-aa62-9924ae2a7e34)

and these are the data on SH
![image](https://github.com/eurodatacube/eodash-catalog/assets/65602207/5eb96b10-bd67-4468-9967-d0d591e35772)

**Comment by lubojr** [comment]
@AlessandroScremin The catalog is currently freshly generated during each PR Merge to main branch and all dates for almost all SH collections that we reference are automatically generated from Sentinel Hub APIs.
The last PR was merged on 2.5.2024 so these data should in principle be in.

I will double check and try to build this collection catalog locally.

**Comment by lubojr** [comment]
Interesting. Now I locally also get a latest date of SH layer as `2024-02-24` for Nagoya POI. (as your SH export shows), so the catalog generation works correctly.

I have double checked the cache eviction on our deployment platform and the corresponding file seems to have been changed correctly on 2.5.2024 during the last catalog generation run, however the new dates were not there for which I can not find any explanation.

Anyway, the next catalog deployment will already automatically update these dates, so I will close this issue.
