### ISSUE TITLE
Add new datasets: STORY EL NINO/HIGH TEMPERATURES

### ISSUE THREAD

**Issue by AparicioSF** [eurodatacube/eodash-catalog#174]
- Surface air temperature anomaly for January 2024 relative to the January average for the period 1991-2020. Data source: ERA5. Credit: Copernicus Climate Change Service/ECMWF - in this [page](https://climate.copernicus.eu/surface-air-temperature-january-2024) is the map however, I'm not able to find the exact location of this dataset...
  - will be used as graphic, no need for integration

- Land Surface Temperature Sentinel-3 SLSTR
  - [x] Data integration 
    - COG being prepared by PLES (Diego), difficulties in preparing chunked data, tricky part should be solved 
    - focus on summer, june, july
  - [x] Yaml configuration
  - [x] eodashboard integration working
  - [x] Missing legend -  to be provided by PLES
   - Should be possible to integrate, if any issues appear Landsat Surface Temperature (TERRA/MODIS) could be used instead

- ECOSTRESS data - night-time surface temperatures, taken in July - [source](https://search.earthdata.nasa.gov/search?q=ecostress&ac=true) 
(one question: why is [global (monthly?) temperature ](https://race.esa.int/?indicator=CDS1_temperature&x=-699480.17545&y=-727337.28553&z=2.32193)available through race but not on dash?)
  - [x] Data integration 
    - @aapopescu will provide data to Diego and let Federico know 
  - [x] Yaml configuration
  - [x] eodashboard integration working
  - [x] issue with SH style (to be updated by PLES)
  - [x] missing legend - based on style (to be updated by PLES)

**Comment by AlessandroScremin** [comment]
Surface air temperature anomaly are only on pdf...are not maps. THe only dataset we can extract are the timeseries (csv) that include Global and European ANomalies, but also global timeseries for each month, year, current values, climatological values and anomalies values

other datasets not investigated yet.

**Comment by santilland** [comment]
Anca to provide additional information, dataset will be added (coming from JAXA)

**Comment by santilland** [comment]
![image](https://github.com/user-attachments/assets/00878a4a-8e77-441b-9767-58e497a27524)
potential data to be integrated from SH

**Comment by AlessandroScremin** [comment]
@aapopescu 
I checked around...THe land surface temperature is a S3 SLSTR L2 product. Currently in Sentinel Hub and in CDSE there are only S3 SLSTR L1B product.

Or we simply use the S3 SLSTR L1B S9 band (that should be a 1km resolution for SST and LST)...but is not  a "real" product (in the sense it is affected by CLouds and some co-registration issues if udnerstood well) or we should look for data providers that provide S3 SLSTR L2 Land Surface Tempertaure.

**Comment by santilland** [comment]
@AlessandroScremin will explore if data available in openEO

**Comment by FedericoRondoni** [comment]
YAML fo the Sentinel-3 dataset LST uploaded here https://github.com/eurodatacube/eodash-catalog/pull/183

**Comment by AlessandroScremin** [comment]
@aapopescu 
cc: @FedericoRondoni @dmoglioni 

we are starting the ignestion of the S3 SLSTR L2 LST into SH. for the moment we are doing it gradually day by day...we are talking around 700/1000 tiles per day.

here an example selecting only the first half day passes (first 12 hrs). 

this is the preliminary result for June 1st

![image](https://github.com/user-attachments/assets/90d6b8fa-6e7e-47da-a366-6a0429ef53e9)

There are some artifacts at the top of the screen (over 60 degrees North) but honestly I was not able to udnerstadn why and how to filter they out.  I would suggest to proceed with the ingestion due to the short time availble and later investigate how to fix these artifacts. What the use really need to use these datasets is the possibility to filter also by time...so a kind of slidebar for time selection is recomended as the data are quite a lot and ascending and descending orbits can overlay if not filtering the time of the day...

**Comment by AlessandroScremin** [comment]
@aapopescu 
@FedericoRondoni @dmoglioni @AparicioSF 

LST products from S3 L2 are beeing ingested slowly but smoothly. 2 or 4 days every day...but it is needed manual triggering of the service...

Every run (2 days) take from 9 hrs to 12 hrs to process and ingest.

Currently all June is ingested. During weekend I can try to ingest 4 or 6 days, but we don't know if the system will crash...

**Comment by dmoglioni** [comment]
SH configurations and legends operational for both ECOSTRESS and Sentinel-3 SLSTR dataset.
cc @aapopescu you can check the related open PR
cc @lubojr

**Comment by FedericoRondoni** [comment]
@AparicioSF to do the collections/NELST_ECOSTRESS_LST MD file

**Comment by aapopescu** [comment]
@santilland can we close?

**Comment by AparicioSF** [comment]
@santilland the markdowns were both done NELST_ECOSTRESS_LST and /SLSTR1_Sentinel-3-SLSTR-L2-LST

**Comment by santilland** [comment]
As far as i can see the data is there https://www.eodashboard.org/explore?indicator=SLSTR1
I think there are some for me strange looking artifacts, but i would propose to open another issue if this is also considered by others to be the case. Closing this issue as done.
