### ISSUE TITLE
Add new datasets: STORY EXTEME POLLUTION (INDIA/PAQUISTAN)

### ISSUE THREAD

**Issue by AparicioSF** [eurodatacube/eodash-catalog#175]
- Carbon monoxide maps - Sentinel-5P
  - [x] Data integration - carbon monoxide N1-CO
  - [x] Yaml configuration
  - [x] eodashboard integration working [link](https://www.eodashboard.org/explore?indicator=N1_CO)

- Fire datasets (VIIRS I-Band) - I think it can be downloaded from here [source](https://firms.modaps.eosdis.nasa.gov/download/)
  - [x] Data integration (Modis_SNPP_2023)
  - [x] Yaml configuration
  - [x] eodashboard integration working [link](https://www.eodashboard.org/explore?indicator=Modis_SNPP_2023)

- Wind dataset (horizontal winds at 100m) - [source](https://cds.climate.copernicus.eu/cdsapp#!/dataset/reanalysis-era5-single-levels?tab=form)
  - [x] Data integration
  - [x] Yaml configuration (in principle working but wrong config)
  - [x] eodashboard integration working (in principle working but wrong config)

- Science Hub Challenge (datasets in Xcube)
  - [x] #192
     - Selviga Sinnathamby-Elie Zoghbi-Natacha Kaminski-[CHALLENGE n°1 extreme air pollution episodes in Northern India and Pakistan] (WInd UV and Tropomi data cubes)
  - [x] Yaml configuration
    - placeholder yaml files have been created for available datasets [here](https://github.com/eurodatacube/eodash-catalog/pull/186)
    - PLES team (@FedericoRondoni) feel free to work on branch to add information to YAML files 
  - [x] eodashboard integration working integration of 3 datasets received [here](https://eodash-trilateral-staging.eox.at/?catalog=sciencehub)

**Comment by AlessandroScremin** [comment]
Carbon monoxide should be already avaialbe as global layer

Fires: VIIRS 375 are avaialbe only till 2021. IF needed for 2023 onlhy MODIS avaialbe and was already ingested in the GEODB

Wind dataset ingested GLOBALLY for 2023.

@FedericoRondoni 
could you please add the yaml and MD file for Fires (MODIS only) and wind Dataset?

here the references:
wind datasets:
VIS_ERA5_SINGLELEVEL_WIND_U_100M_GLOBAL  >  ac99bb32-a94d-4f4f-b8dd-c0098ca07665
VIS_ERA5_SINGLELEVEL_WIND_V_100M_GLOBAL  >  f70007f3-da80-4c23-b3ae-adc8634ca7c7

**Comment by santilland** [comment]
Needs to be for 2023, will be checked for Fire datasets (VIIRS I-Band)

**Comment by FedericoRondoni** [comment]
@santilland @lubojr, concerning the Fire story MODIS dataset, I have checked, and the YAML file is already present. I think you created it.
I have applied some changes related to the details of the dataset and added the GeoDB ones as resources. I don't know what the Collection-only resource is or if the GeoDB is correctly accessed (it creates some issues). It would be great if you could clarify this point for this and future indicators.

In any case, I think that for this story, we are good.

Here you can find the pull request: https://github.com/eurodatacube/eodash-catalog/pull/183
And here is the one for the assets: https://github.com/eurodatacube/eodash-assets/pull/54

**Comment by santilland** [comment]
Hello @FedericoRondoni yes, you are correct, Lubo already integrated this dataset. The collection-only resource is something we use when special functionality is needed in the client that has not yet been mapped to STAC based logic. So, the MODIS dataset combines multiple datasets using an area selection. So not all the data in geodb can be shown at once.
We are working on defining a STAC based process definition that will replace this approach in the future. So for uncommon, non standard data integration we can take care of integration.
You can find the current integration here:
https://www.eodashboard.org/explore?indicator=Modis_SNPP_2023
I will remove the for now unnecessary Resource configuration you added to the Yaml file, which seems to create an issue.

**Comment by santilland** [comment]
@FedericoRondoni i pushed a commit to your branch, make sure you do a pull before continuing your edits

**Comment by FedericoRondoni** [comment]
> @FedericoRondoni i pushed a commit to your branch, make sure you do a pull before continuing your edits

Hi @santilland I'm not sure I know what you mean. I don't see any action from my side to be done. Sorry in advance if it is a silly question, but I still don't know all the GitHub aspects.

**Comment by santilland** [comment]
@FedericoRondoni if you are working directly on github, all should be fine, sorry for the confusion. It would only be necessary to do a git pull if you are working in the branch locally on your computer and then pushing the changes

**Comment by aapopescu** [comment]
@FedericoRondoni , here is the JN with the information for the yamls of the "maps generated from study" 
[3_OpenChallengeNotebook[RMSH]-[Challenge1]Sinnathamby_Kaminski_Zoghbi.ipynb.zip](https://github.com/user-attachments/files/16599721/3_OpenChallengeNotebook.RMSH.-.Challenge1.Sinnathamby_Kaminski_Zoghbi.ipynb.zip)

**Comment by FedericoRondoni** [comment]
YAML files ready and pulled with this request https://github.com/eurodatacube/eodash-catalog/pull/186

**Comment by FedericoRondoni** [comment]
@AparicioSF currently working on the description of the indicators SHC1_era5_u_winds SHC2_era5_v_winds

**Comment by FedericoRondoni** [comment]
@santilland @lubojr description of SHC1 and SHC2 created and uploaded. Commits already merged
