### ISSUE TITLE
Implement possibility of defining a grouped catalog collection entry

### ISSUE THREAD

**Issue by santilland** [eurodatacube/eodash-catalog#54]
Currently the collections defined in the catalog file are expected to be individual collections, allowing adding multiple collections could support a use case where an "indicator" in the client is composed of multiple collections (this could be for different locations).
The main question would be, what information is shown when loading the parent collection that references to the integrated ones

**Comment by santilland** [comment]
Maybe a "parent" collection can be defined with some metadata information, e.g.

```
collections:
  - parent_collection
    children:
      - child_collection_1
      - child_collection_2
  - other_collection
  - ...
```

**Comment by lubojr** [comment]
Similar approach as the "locations" concept in https://github.com/eurodatacube/eodash-catalog/blob/328b76abb7ac8ec58f0e6d9d33f6c07afc5babb7/collections/E13c_cruises_impact.yaml#L19
that does "area" filtering on a collection

**Comment by santilland** [comment]
If we assume that an added collection should only represent one location, which we can then "force" by applying filtering to an area, i think the Locations approach works very well.
I have done an initial implementation in the multicollection branch https://github.com/eurodatacube/eodash-catalog/tree/multicollection
