### ISSUE TITLE
Add configuration option to not generate items when creating catalog

### ISSUE THREAD

**Issue by santilland** [eurodatacube/eodash-catalog#76]
Some collections seem to be to massive to be generated in an acceptable time span, we should allow setting a special flag to allow defining collection time extent, but not to generate the items themselves?
Needs investigation, related to pull request #69

**Comment by lubojr** [comment]
Introducing `Disable_Items: true` per Endpoint in https://github.com/eurodatacube/eodash-catalog/pull/69 which disables generation of items

**Comment by lubojr** [comment]
Current workaround lets client to generate the times as they fit and current collection placeholder is enough as is.

Next step would be to evaluate if we should actually push the times to the time extent array - the same as with the bbox extent, the first element describes the total coverage, and next array items define smaller regions withing the total coverage. This should be faster than having to generate individual items for ~16k dates for each of three GCOM-W placeholder collections.

**Comment by lubojr** [comment]
eodash v4 client works with disable generation of items, eodash v5 should involve limitting the presented datetime range
closing the issue
