### ISSUE TITLE
RACE catalog CMEMS black sea and mediterannean do not load

### ISSUE THREAD

**Issue by lubojr** [eurodatacube/eodash-catalog#86]
Following three collections referenced in RACE do not work in STAC Browser.

Needs investigation

https://radiantearth.github.io/stac-browser/#/external/eurodatacube.github.io/eodash-catalog/RACE/ocean_colour_plankton_black_sea/collection.json

https://radiantearth.github.io/stac-browser/#/external/eurodatacube.github.io/eodash-catalog/RACE/ocean_colour_plankton_mediterranean/collection.json

https://radiantearth.github.io/stac-browser/#/external/eurodatacube.github.io/eodash-catalog/RACE/ocean_colour_plankton_atlantic/collection.json

**Comment by lubojr** [comment]
Data got migrated
https://data.marine.copernicus.eu/product/OCEANCOLOUR_GLO_BGC_L4_MY_009_104/services 

https://wmts.marine.copernicus.eu/teroWmts/OCEANCOLOUR_GLO_BGC_L4_MY_009_104/cmems_obs-oc_glo_bgc-plankton_my_l4-multi-4km_P1M_202311?request=GetCapabilities&service=WMS

**Comment by AlessandroScremin** [comment]
@lubojr 
Im checking...is not that simple withoput the source anymore...for sure we need from the description dayli products...
i will ask the scientist here...I will keep you updated

**Comment by AlessandroScremin** [comment]
@lubojr 

contacted the scientific Team for the new endpoints, Waiting inputs

**Comment by aapopescu** [comment]
I believe these are the datasets 

- https://data.marine.copernicus.eu/viewer/expert?view=datasetServices&dataset=OCEANCOLOUR_ATL_BGC_L4_NRT_009_116 - ATLANTIC
- https://data.marine.copernicus.eu/viewer/expert?view=dataset&dataset=OCEANCOLOUR_BLK_BGC_L4_NRT_009_152 – BLACK SEA
- https://data.marine.copernicus.eu/viewer/expert?view=dataset&dataset=OCEANCOLOUR_MED_BGC_L3_NRT_009_141 - MDITERRANEAN

**Comment by lubojr** [comment]
@aapopescu Thank you for the feedback. We will have a look at integrating those three.

**Comment by lubojr** [comment]
New WMTS endpoints integrated in https://github.com/eurodatacube/eodash-catalog/pull/151

**Comment by lubojr** [comment]
PR is merged.
